### ISSUE TITLE
Make Theme Print Friendly

### ISSUE THREAD

**Issue by ishu3101** [xriley/Orbit-Theme#9]
How do you make the theme print friendly so that you could use the same resume as most jobs required resume to be in either pdf or word document format?

**Comment by jerezapo** [comment]
I'm not the theme developer but I thought I would chime on.

To answer you original question: How do you move the sidebar from the right side to the left side?
I'm not the theme developer but you can edit styles.css file. 

Update the following two classes:

.main-wrapper {
  background: #fff;
  padding: 60px;
  padding-right: 100px; /*modify: less padding on left, to spread out content*/
  padding-left: 300px; /*add: left padding to move the main content area over*/
}

.sidebar-wrapper {
  background: #42A8C0;
  position: absolute;
  /* right: 0; */ /*comment out*/
  width: 240px;
  height: 100%;
  min-height: 800px;
  color: #fff;
}

As for printer friendly, I would take a screenshot using a chrome extension, like OpenScreensoot https://www.openscreenshot.com/

**Comment by ishu3101** [comment]
I figured out how to change the sidebar from right to left after I posted the question. That's why I changed the original question. Thanks for answering that question any way.

I do not want a screenshot. I would like to take this web resume and have the same resume available in pdf format as this is the format most employers want when looking for job.

**Comment by xriley** [comment]
This theme is not intended for printing. 

I've released a [free Sketch design template ](https://themes.3rdwavemedia.com/resources/sketch-template/orbit-sketch-sketch-resume-template-for-developers/) for this theme so you can provide a link or CTA button on your online resume for people to download/print.
